server:
    port: 8080

spring:
    application:
      name: workout
    data:
      mongodb:
        host: localhost #default port = 27017
        username: mongo
        password: mongo
        database: test