version: '3.3'
services:
#  gateway:
#    container_name: gateway
#    build:
#      context: .
#      dockerfile: docker/gateway/Dockerfile-run
#    ports:
#      - 8080:8080
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: docker/user-service/Dockerfile-run
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - user-network
      - kafka-network
    depends_on:
      - mongo-user
      - kafka

  mongo-user:
    container_name: mongo-user
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    volumes:
      - mongo-user:/data/db
#    ports:
#      - 27017:27017
    networks:
      - user-network
      - kafka-network
#    restart: unless-stopped

  workout-service:
    container_name: workout-service
    build:
      context: .
      dockerfile: docker/workout-service/Dockerfile-run
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - workout-network
      - kafka-network
    depends_on:
      - mongo-workout
      - kafka

  mongo-workout:
    container_name: mongo-workout
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: workout
      MONGO_INITDB_ROOT_PASSWORD: workout
    volumes:
      - mongo-workout:/data/db
#    ports:
#      - 27017:27017
    networks:
      - workout-network
      - kafka-network
#    restart: unless-stopped

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    depends_on:
      - zookeeper
    networks:
      - kafka-network

networks:
  user-network:
    driver: bridge
  workout-network:
    driver: bridge
  kafka-network:
    driver: bridge


volumes:
  mongo-user:
  mongo-workout: