version: '3.3'
services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile-run
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: docker/user-service/Dockerfile-run
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - user-network
    depends_on:
      - mongo-user

  mongo-user:
    container_name: mongo-user
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    volumes:
      - mongo-user:/data/db
    ports:
      - 27017:27017
    networks:
      - user-network
#    restart: unless-stopped

  workout-service:
    container_name: workout-service
    build:
      context: .
      dockerfile: docker/workout-service/Dockerfile-run
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - workout-network
    depends_on:
      - mongo-workout

  mongo-workout:
    container_name: mongo-workout
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: workout
      MONGO_INITDB_ROOT_PASSWORD: workout
    volumes:
      - mongo-workout:/data/db
#    ports:
#      - 27017:27017
    networks:
      - workout-network
#    restart: unless-stopped

networks:
  user-network:
    driver: bridge
  workout-network:
    driver: bridge


volumes:
  mongo-user:
  mongo-workout: