version: '3.3'
services:
  mongo:
    container_name: mongoDB
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo
    restart: unless-stopped

  workout-service:
    container_name: workout-service
    build:
      context: .
      dockerfile: docker/workout-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - mongo
    depends_on:
      - mongo

networks:
  mongo:
    driver: bridge

volumes:
  mongo: