version: '3.3'
services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile-run
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=production

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: docker/user-service/Dockerfile-run
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - user-network
      - kafka-network
    depends_on:
      - kafka

  workout-service:
    container_name: workout-service
    build:
      context: .
      dockerfile: docker/workout-service/Dockerfile-run
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - workout-network
      - kafka-network
    depends_on:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    depends_on:
      - zookeeper
    networks:
      - kafka-network

networks:
  user-network:
    driver: bridge
  workout-network:
    driver: bridge
  kafka-network:
    driver: bridge