server:
  port: 8080

spring:
  profiles:
    active: development
  application:
    title: gateway
    version: 1.0
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/644617e7-1801-4ee3-838c-2765e373cfde/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/644617e7-1801-4ee3-838c-2765e373cfde/v2.0
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

---
spring:
  config:
    activate:
      on-profile: production
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: workout-service
          uri: http://workout-service:8082
          predicates:
            - Path=/workout/**
          filters:
            - RewritePath=/workout/(?<segment>.*), /$\{segment}
---
spring:
  config:
    activate:
      on-profile: development
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: workout-service
          uri: http://localhost:8082
          predicates:
            - Path=/workout/**
          filters:
            - RewritePath=/workout/(?<segment>.*), /$\{segment}

---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: workout-service
          uri: http://workout-service
          predicates:
            - Path=/workout/**
          filters:
            - RewritePath=/workout/(?<segment>.*), /$\{segment}
