server:
  port: 8080

spring:
  application:
    title: gateway
    version: 1.0
    name: gateway


  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
        routes:
          - id: workout-service
            uri: http://localhost:8081/
            predicates:
              - Path=/workout/**
        httpclient:
          wiretap: true
          httpserver:
            wiretap: true
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE