server:
    port: 8081

spring:
  kafka:
    bootstrap-servers: kafka:9092

  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://user:user@mongo-user:27017
      database: user

mongodb.encrypt:
  keys:
    - version: 1
      key: hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=