spring:
  profiles:
    active: development
  application:
    name: user-service

server:
  port: 8081

mongodb.encrypt:
  keys:
    - version: 1
      key: ${ENCRYPT_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
---
spring:
  config:
    activate:
      on-profile: atlas
  kafka:
    bootstrap-servers: kafka-service:9092
  data:
    mongodb:
      uri: ${ATLAS_CONNECTION_STRING}
      database: ${USER_DATABASE_NAME}

---
spring:
  config:
    activate:
      on-profile: development
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://user:user@localhost:27017
      database: ${USER_DATABASE_NAME}

---
spring:
  config:
    activate:
      on-profile: production
  kafka:
    bootstrap-servers: kafka-service:9092
  data:
    mongodb:
      uri: mongodb://user:user@mongo-user:27017
      database: ${USER_DATABASE_NAME}

---
spring:
  config:
    activate:
      on-profile: azure
  kafka:
    bootstrap-servers: kafka-service:9092
  data:
    mongodb:
      uri: ${AZURE_CONNECTION_STRING}
      database: ${USER_DATABASE_NAME}