spring:
  profiles:
    active: development
  application:
    name: user-service

server:
  port: 8081

mongodb.encrypt:
  keys:
    - version: 1
      key: hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=
---
spring:
  config:
    activate:
      on-profile: production
  kafka:
    bootstrap-servers: kafka-service:9092
  data:
    mongodb:
      uri: mongodb+srv://Dizziness1959:5hLJx9%25%23AiW%5E%24m@sportscentre.hn5hb73.mongodb.net/?retryWrites=true&w=majority
      database: user

---
spring:
  config:
    activate:
      on-profile: development
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      uri: mongodb://user:user@mongo-user:27017
      database: user

---
spring:
  config:
    activate:
      on-profile: azure
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      uri: mongodb://freekvanlier:KNlu83DMFNyutDCyq9p6olIHQo6uVtjh2uOq2iudQM7cfPOGhX42p1o4Z2aF6Y1Xohoqj7KxT6J7ACDby2nU1w==@freekvanlier.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@freekvanlier@
      database: user