apiVersion: v1
kind: Namespace
metadata:
  name: sportscentre
  labels:
    name: sportscentre
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: sportscentre
  labels:
    app: gateway
    tier: backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gateway
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: sportscentre
spec:
  selector:
    matchLabels:
      app: gateway
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
    spec:
      containers:
        - name: gateway
          image: ghcr.io/freekvlier/sportscentre/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: spring_profiles_active
              value: kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: workout-service
  namespace: sportscentre
  labels:
    app: workout-service
    tier: backend
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: workout-service
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-service
  namespace: sportscentre
spec:
  selector:
    matchLabels:
      app: workout-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: workout-service
        tier: backend
    spec:
      containers:
        - name: workout-service
          image: ghcr.io/freekvlier/sportscentre/workout-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: spring_profiles_active
              value: atlas
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: sportscentre
  labels:
    app: user-service
    tier: backend
spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: user-service
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: sportscentre
spec:
  selector:
    matchLabels:
      app: user-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
    spec:
      containers:
        - name: user-service
          image: ghcr.io/freekvlier/sportscentre/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: spring_profiles_active
              value: atlas
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: sportscentre
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - name: '9092'
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: sportscentre
  labels:
    app: kafka
spec:
  serviceName: kafka-service
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: doughgle/kafka-kraft
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: REPLICAS
              value: '3'
            - name: SERVICE
              value: kafka-service
            - name: NAMESPACE
              value: sportscentre
            - name: SHARE_DIR
              value: /mnt/kafka
            - name: CLUSTER_ID
              value: oh-sxaDRTcyAr6pFRbXyzA
            - name: DEFAULT_REPLICATION_FACTOR
              value: '3'
            - name: DEFAULT_MIN_INSYNC_REPLICAS
              value: '1'