apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: redis
    tier: backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gateway
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
    spec:
      containers:
        - name: gateway
          image: ghcr.io/freaxy123/sportscentre/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: workout-service
  labels:
    app: workout-service
    tier: backend
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: workout-service
    tier: backend

---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: workout-service
spec:
  selector:
    matchLabels:
      app: workout-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: workout-service
        tier: backend
    spec:
      containers:
        - name: workout-service
          image: ghcr.io/freaxy123/sportscentre/workout-service:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    tier: backend
spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: user-service
    tier: backend

---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
    spec:
      containers:
        - name: workout-service
          image: ghcr.io/freaxy123/sportscentre/user-service:latest
          ports:
            - containerPort: 8081
---
#Kafka
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:latest
          ports:
            - containerPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-deployment-0.kafka-service
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
