apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: redis
    tier: backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gateway
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
    spec:
      containers:
        - name: gateway
          image: ghcr.io/freaxy123/sportscentre/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: workout-service
  labels:
    app: workout-service
    tier: backend
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: workout-service
    tier: backend

---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: workout-service
spec:
  selector:
    matchLabels:
      app: workout-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: workout-service
        tier: backend
    spec:
      containers:
        - name: workout-service
          image: ghcr.io/freaxy123/sportscentre/workout-service:latest
          ports:
            - containerPort: 8082
---