name: docker-compose

on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened]

env:
  REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          COMPOSE_PROJECT_NAME: "sportscentre"
          AZURE_SET_URI: ${{ secrets.AZURE_SET_URI }}
          AZURE_ISSUER_URI: ${{ secrets.AZURE_ISSUER_URI }}
          AZURE_AUDIENCE: ${{ secrets.AZURE_AUDIENCE }}
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
          ATLAS_CONNECTION_STRING: ${{ secrets.ATLAS_CONNECTION_STRING }}
          AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
          USER_DATABASE_NAME: ${{ secrets.USER_DATABASE_NAME }}
          WORKOUT_DATABASE_NAME: ${{ secrets.WORKOUT_DATABASE_NAME }}

      - name: Build and run docker compose stack
        run: docker compose up -d --build
      - name: Check running containers
        run: docker ps -a