spring:
  profiles:
    active: development
  application:
    name: workout-service
  kafka:
      consumer:
        group-id: workout-service
        auto-offset-reset: earliest
  main:
      allow-bean-definition-overriding: true
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

mongodb.encrypt:
  keys:
    - version: 1
      key: ${ENCRYPT_KEY}
---
spring:
  config:
    activate:
      on-profile: atlas
  kafka:
    consumer:
      bootstrap-servers:  kafka-service:9092
  data:
    mongodb:
      uri: ${ATLAS_CONNECTION_STRING}
      database: ${WORKOUT_DATABASE_NAME}

---
spring:
  config:
    activate:
      on-profile: production
  kafka:
    consumer:
      bootstrap-servers:  kafka-service:9092
  data:
    mongodb:
      uri: mongodb://workout:workout@mongo-workout:27017
      database: ${WORKOUT_DATABASE_NAME}

---
spring:
  config:
    activate:
      on-profile: development
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://workout:workout@localhost:27017
      database: ${WORKOUT_DATABASE_NAME}
---
spring:
  config:
    activate:
      on-profile: azure
  kafka:
    consumer:
      bootstrap-servers: kafka-service:9092
  data:
    mongodb:
      uri: ${AZURE_CONNECTION_STRING}
      database: user