server:
    port: 8082

spring:
  kafka:
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: kafka:9092

  application:
    name: workout-service
  data:
    mongodb:
      uri: mongodb://workout:workout@mongo-workout:27017
      database: workout
        